package de.matrix.pvnikamod.main;

import de.matrix.pvnikamod.config.Config;
import de.matrix.pvnikamod.config.RuntimeSettings;
import de.matrix.pvnikamod.listener.*;
import de.matrix.pvnikamod.renderer.HitboxRenderer;
import de.matrix.pvnikamod.modutils.ZoomUtils;
import de.matrix.pvnikamod.renderer.IngameRenderer;
import de.matrix.pvnikamod.utils.Pinger;
import net.minecraft.client.Minecraft;
import net.minecraft.client.settings.KeyBinding;
import net.minecraft.util.EnumChatFormatting;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.ClientCommandHandler;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.registry.ClientRegistry;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.File;

@Mod(
        modid = "pvnikamod",
        name = "Pvnika Mod",
        version = "beta",
        acceptedMinecraftVersions = "[1.8.9]",
        clientSideOnly = true
)
public class PvnikaMod {

    public static final String MODID = "pvnikamod";
    public ModMetadata modMetadata;
    public static File FOLDER_FILE;
    public static final File CONFIG_FILE;
    public static final File MODULES_FILE;
    private Config config;
    public static final String PREFIX = "[PvnikaMod] ";
    public Minecraft mc;
    public static PvnikaMod mod;
    public static Logger logger = LogManager.getLogger("PvnikaMod");
    private Events events;
    private Chat chat;
    public TabList tabList;
    public ZoomUtils zoomUtils;
    public Implementation implementation;
    public HitboxRenderer hitboxRenderer;
    public IngameRenderer ingameRenderer;
    public Pinger pinger;

    public static KeyBinding openPvnikaGui = new KeyBinding("Open Pvnika GUI", 54, "Pvnika Mod");
    public static KeyBinding zoomKey = new KeyBinding("Zoom", 0, "Pvnika Mod");
    public static KeyBinding primaryTargetKey = new KeyBinding("Set Primary Target", 0, "Pvnika Mod");
    public static final ResourceLocation pvnikaLogo = new ResourceLocation(PvnikaMod.MODID,"images/logo.png");
    public static final ResourceLocation pvnikaHeader = new ResourceLocation(PvnikaMod.MODID,"images/header.png");



    @EventHandler
    public void preInit(FMLPreInitializationEvent event){
        sendLog("Initializing PvnikaMod");
        this.modMetadata = event.getModMetadata();
        this.modMetadata.autogenerated = false;
        this.modMetadata.name = EnumChatFormatting.BLUE + "PvnikaMod";
        this.modMetadata.version = EnumChatFormatting.RED + "b0.9.7";
        this.modMetadata.description = EnumChatFormatting.WHITE + "A PvP Mod that has a lot of features like other clients, but this is mod doesn't require a unique client and can be combined with a lot of other mods. Feel free to create a feature request on GitHub :)\n" + EnumChatFormatting.LIGHT_PURPLE + "~matrix";
        this.modMetadata.credits = EnumChatFormatting.GREEN + "by MatrixCodeDE";
        this.modMetadata.logoFile = "assets/pvnikamod/images/logo.png";
        PvnikaMod.mod = PvnikaMod.this;
        PvnikaMod.this.mc = Minecraft.getMinecraft();

        sendLog("Loading Config");
        this.config = new Config(CONFIG_FILE, MODULES_FILE);

        this.config.loadConfig();
        this.config.igModules.loadModuleConfig();

        RuntimeSettings.init();

        sendLog("Successfully loaded Config");
        sendLog("Loading Mods");
        ClientRegistry.registerKeyBinding(openPvnikaGui);
        ClientRegistry.registerKeyBinding(zoomKey);
        ClientRegistry.registerKeyBinding(primaryTargetKey);
        this.zoomUtils = new ZoomUtils();
        this.hitboxRenderer = new HitboxRenderer();
        this.pinger = new Pinger();
        sendLog("Successfully loaded Mods");
        sendLog("Loading mixins");
    }


    @EventHandler
    public void init(FMLInitializationEvent event) {
        this.events = new Events();
        this.chat = new Chat();
        this.tabList = new TabList(this.mc, this.mc.ingameGUI);
        this.implementation = new Implementation();
        MinecraftForge.EVENT_BUS.register(this.events);
        MinecraftForge.EVENT_BUS.register(this.chat);
        MinecraftForge.EVENT_BUS.register(this.tabList);
        this.ingameRenderer = new IngameRenderer();
        ClientCommandHandler.instance.registerCommand(new Commands());
        sendLog("Successfully loaded mixins");
        sendLog("Initialization complete");
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event){
    }



    static {
        FOLDER_FILE = new File(Minecraft.getMinecraft().mcDataDir, "pvnika");
        CONFIG_FILE = new File(FOLDER_FILE, "pvnikamod.cfg");
        MODULES_FILE = new File(FOLDER_FILE, "pvnikamodules.cfg");
    }

    public static PvnikaMod getInstance() {
        if(mod == null) {
            mod = new PvnikaMod();
        }
        return mod;
    }

    public Config getConfig() {
        return this.config;
    }

    public static void sendLog(String log){
        logger.info(PREFIX + log);
    }
}
